title: Harim Jang
description: Backend & iOS Developer
site_title: '@ashjang - Harim Jang'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: ashjang
blog_url: https://harimms.tistory.com
email: vkdvkdgkfla@naver.com

# absolute or relative
profile_picture: assets/images/me.jpg

# Google Analytics ID
google_analytics: 